#!/bin/bash
#
# container ENVs

all_proxy=socks5://localhost:1080

NODES=${NODES:-1}
MODEL_PATH=${MODEL_PATH:-/d/models/deepseek-R1-0528-w8a8}
MODEL_NAME=${MODEL_NAME:-DeepSeek-R1-0528}
echo NODES: $NODES
echo MODEL_PATH is: $MODEL_PATH
echo MODEL_NAME is: $MODEL_NAME

declare -A addr
addr=(
    [gx1]=172.20.84.67
    [gx2]=172.20.84.77
    [gx3]=172.20.84.189
    [gx4]=172.20.84.50
)
echo hostname is: $HOSTNAME
echo IP is: ${addr[$HOSTNAME]}

echo export ENVs

export USE_MULTI_BLOCK_POOL=1
export OMP_PROC_BIND=false
export OMP_NUM_THREADS=10
export PYTORCH_NPU_ALLOC_CONF=expandable_segments:True
export ACL_OP_INIT_MODE=1
export TRITON_ALL_BLOCKS_PARALLEL=1

if [ $NODES -gt 1 ]; then
    # this obtained through ifconfig
    # nic_name is the network interface name corresponding to local_ip of the current node
    nic_name="xxx"
    local_ip="xxx"

    # The value of node0_ip must be consistent with the value of local_ip set in node0 (master node)
    node0_ip="xxxx"

    export HCCL_OP_EXPANSION_MODE="AIV"
    export HCCL_IF_IP=$local_ip
    export GLOO_SOCKET_IFNAME=$nic_name
    export TP_SOCKET_IFNAME=$nic_name
    export HCCL_SOCKET_IFNAME=$nic_name
    export HCCL_BUFFSIZE=200
    export HCCL_CONNECT_TIMEOUT=120
    export HCCL_INTRA_PCIE_ENABLE=1
    export HCCL_INTRA_ROCE_ENABLE=0
fi
