#!/bin/bash
#
# container ENVs

all_proxy=socks5://localhost:1080

NODES=${NODES:-1}
MODEL_PATH=${MODEL_PATH:-/d/models/deepseek-R1-0528-w8a8}
MODEL_NAME=${MODEL_NAME:-DeepSeek-R1-0528}
echo NODES: $NODES
echo MODEL_PATH is: $MODEL_PATH
echo MODEL_NAME is: $MODEL_NAME

declare -A addr
addr=(
    [gx1]=172.20.84.67
    [gx2]=172.20.84.77
    [gx3]=172.20.84.189
    [gx4]=172.20.84.50
)
echo hostname is: $HOSTNAME
echo IP is: ${addr[$HOSTNAME]}

echo export ENVs

export USE_MULTI_BLOCK_POOL=1
export OMP_PROC_BIND=false
export OMP_NUM_THREADS=10
export PYTORCH_NPU_ALLOC_CONF=expandable_segments:True
export ACL_OP_INIT_MODE=1
export TRITON_ALL_BLOCKS_PARALLEL=1
