#!/bin/bash
#
# container ENVs

CONF_PATH=${CONF_PATH:-/gx3/conf/config.json}
MULTI=${MULTI:-1}
MODEL_PATH=${MODEL_PATH:-/d/models/deepseek-R1-0528-bf16}
MODELNAME=${MODELNAME:-DeepSeek-R1-0528}
echo CONF_PATH is $CONF_PATH
echo MULTI: $MULTI
echo MODEL_PATH is: $MODEL_PATH

declare -A addr
addr=(
    [gx1]=172.20.84.67
    [gx2]=172.20.84.77
    [gx3]=172.20.84.189
    [gx4]=172.20.84.50
)
echo hostname is: $HOSTNAME
echo IP is: ${addr[$HOSTNAME]}

mindie_ver=$(readlink /usr/local/Ascend/mindie/latest)
echo MindIE version: $mindie_ver

echo export ENVs

# see https://www.hiascend.com/document/detail/zh/mindie/21RC2/mindieservice/servicedev/mindie_service0300.html
export ASCEND_DIR=/usr/local/Ascend

source $ASCEND_DIR/ascend-toolkit/set_env.sh
source $ASCEND_DIR/nnal/atb/set_env.sh
source $ASCEND_DIR/atb-models/set_env.sh
source $ASCEND_DIR/mindie/set_env.sh

export MIES_INSTALL_PATH=$ASCEND_DIR/mindie/latest/mindie-service
export LD_LIBRARY_PATH=${MIES_INSTALL_PATH}/lib:${MIES_INSTALL_PATH}/lib/grpc:${LD_LIBRARY_PATH}
export PYTHONPATH=${MIES_INSTALL_PATH}/bin:${PYTHONPATH}
export ATB_OPERATION_EXECUTE_ASYNC=1
export TASK_QUEUE_ENABLE=1
# mindie-service日志
export MINDIE_LOG_TO_STDOUT=1
export MINDIE_LOG_TO_FILE=1
export MINDIE_LOG_LEVEL=ERROR
# MindIE service will chmod 750 on both MINDIE_LOG_PATH and its parent, so add a dir `local` to absorb this
export MINDIE_LOG_PATH=/d/log/local/mindie
# 运行时日志
export ASCEND_SLOG_PRINT_TO_STDOUT=0
export ASCEND_GLOBAL_LOG_LEVEL=3
export ASCEND_GLOBAL_EVENT_ENABLE=1
# 模型库日志
export ASDOPS_LOG_TO_FILE=1
export ASDOPS_LOG_TO_STDOUT=1
export ASDOPS_LOG_LEVEL=ERROR

# unset deprecated ENVs to aviod log complain
unset ATB_LOG_TO_FILE # deprecated, use MINDIE_LOG_TO_FILE 
unset ATB_LOG_TO_FILE_FLUSH
unset ATB_LOG_TO_STDOUT # deprecated, use MINDIE_LOG_TO_STDOUT 
unset ATB_LOG_LEVEL # deprecated, use MINDIE_LOG_LEVEL 
unset OCK_LOG_LEVEL # deprecated, use MINDIE_LOG_LEVEL 
unset OCK_LOG_TO_STDOUT # deprecated, use MINDIE_LOG_TO_STDOUT 
unset MINDIE_LLM_LOG_LEVEL # deprecated, use MINDIE_LOG_LEVEL 
unset MINDIE_LLM_PYTHON_LOG_TO_STDOUT # deprecated, use MINDIE_LOG_TO_STDOUT
unset MINDIE_LLM_LOG_TO_STDOUT # deprecated, use MINDIE_LOG_TO_STDOUT 
unset MINDIE_LLM_PYTHON_LOG_PATH # deprecated, use MINDIE_LOG_PATH 
unset MINDIE_LLM_PYTHON_LOG_LEVEL # deprecated, use MINDIE_LOG_LEVEL 
unset MINDIE_LLM_PYTHON_LOG_TO_FILE # deprecated, use MINDIE_LOG_TO_FILE 
unset MINDIE_LLM_LOG_TO_FILE # deprecated, use MINDIE_LOG_TO_FILE 
unset RANKTABLEFILE # 2.0

export MIES_CONTAINER_IP=${addr[$HOSTNAME]}

if [ $MULTI -eq 1 ]; then
    export RANK_TABLE_FILE=/gx3/conf/rank_table.json
    export HCCL_DETERMINISTIC=true
    export ATB_LLM_HCCL_ENABLE=1
    export ATB_LLM_COMM_BACKEND="hccl"
    export HCCL_CONNECT_TIMEOUT=7200 # 该环境变量需要配置为整数，取值范围[120,7200]，单位s
    # 双机：
    #export WORLD_SIZE=16
    # 四机：
    export WORLD_SIZE=32
    export HCCL_EXEC_TIMEOUT=0
    export HCCL_BUFFSIZE=120
fi

# 解决权重加载过慢问题
export OMP_NUM_THREADS=1
# 设置显存比
export NPU_MEMORY_FRACTION=0.96

# [error] [1114] [reshape_and_cache_operation.cpp:292] ReshapeAndCacheOperation_2_0_14 key and keycache headSize should be same, value and value cache headSize should be same
export MIES_USE_MB_SWAPPER=1
export MIES_RECOMPUTE_THRESHOLD=0.5
